<a href="https://colab.research.google.com/github/topkidbiola/python_practice/blob/main/Moshood_Abdulrasaq_Specialization_Week11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import Libraries

In [ ]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor,GradientBoostingRegressor

#1. Load Dataset

In [ ]:
filepath = '/content/drive/MyDrive/DeepTech_Ready_Cohort3/Graduation_Assessment/SuperMarket Analysis.csv'
df = pd.read_csv(filepath)

# Dataset Inspection

In [ ]:
print(df.shape)
print(df.info())
print(df.head())

(1000, 17)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Invoice ID               1000 non-null   object
 1   Branch                   1000 non-null   object
 2   City                     1000 non-null   object
 3   Customer type            1000 non-null   object
 4   Gender                   1000 non-null   object
 5   Product line             1000 non-null   object
 6   Unit price               1000 non-null   float64
 7   Quantity                 1000 non-null   int64
 8   Tax 5%                   1000 non-null   float64
 9   Sales                    1000 non-null   float64
 10  Date                     1000 non-null   object
 11  Time                     1000 non-null   object
 12  Payment                  1000 non-null   object
 13  cogs                     1000 non-null   float64
 14  gross margin percentage  1000 non-null   float64
 15  gross income             1000 non-null   float64
 16  Rating                   1000 non-null   float64
dtypes: float64(7), int64(1), object(9)
memory usage: 132.9+ KB
None
    Invoice ID Branch       City Customer type  Gender  \
0  750-67-8428   Alex     Yangon        Member  Female
1  226-31-3081   Giza  Naypyitaw        Normal  Female
2  631-41-3108   Alex     Yangon        Normal  Female
3  123-19-1176   Alex     Yangon        Member  Female
4  373-73-7910   Alex     Yangon        Member  Female

             Product line  Unit price  Quantity   Tax 5%     Sales       Date  \
0       Health and beauty       74.69         7  26.1415  548.9715   1/5/2019
1  Electronic accessories       15.28         5   3.8200   80.2200   3/8/2019
2      Home and lifestyle       46.33         7  16.2155  340.5255   3/3/2019
3       Health and beauty       58.22         8  23.2880  489.0480  1/27/2019
4       Sports and travel       86.31         7  30.2085  634.3785   2/8/2019

          Time      Payment    cogs  gross margin percentage  gross income  \
0   1:08:00 PM      Ewallet  522.83                 4.761905       26.1415
1  10:29:00 AM         Cash   76.40                 4.761905        3.8200
2   1:23:00 PM  Credit card  324.31                 4.761905       16.2155
3   8:33:00 PM      Ewallet  465.76                 4.761905       23.2880
4  10:37:00 AM      Ewallet  604.17                 4.761905       30.2085

   Rating
0     9.1
1     9.6
2     7.4
3     8.4
4     5.3

# Statistical Summary

In [ ]:
df.describe()

,Unit price,Quantity,Tax 5%,Sales,cogs,gross margin percentage,gross income,Rating
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1.000000e+03,1000.000000,1000.00000
mean,55.672130,5.510000,15.379369,322.966749,307.58738,4.761905e+00,15.379369,6.97270
std,26.494628,2.923431,11.708825,245.885335,234.17651,6.131498e-14,11.708825,1.71858
min,10.080000,1.000000,0.508500,10.678500,10.17000,4.761905e+00,0.508500,4.00000
25%,32.875000,3.000000,5.924875,124.422375,118.49750,4.761905e+00,5.924875,5.50000
50%,55.230000,5.000000,12.088000,253.848000,241.76000,4.761905e+00,12.088000,7.00000
75%,77.935000,8.000000,22.445250,471.350250,448.90500,4.761905e+00,22.445250,8.50000
max,99.960000,10.000000,49.650000,1042.650000,993.00000,4.761905e+00,49.650000,10.00000

In [ ]:
df.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29:00 AM,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3

# Target Variable

In [ ]:
y = df['Sales']
y

0       548.9715
1        80.2200
2       340.5255
3       489.0480
4       634.3785
         ...
995      42.3675
996    1022.4900
997      33.4320
998      69.1110
999     649.2990
Name: Sales, Length: 1000, dtype: float64

# Features(drop target and identifier)

In [ ]:
X = df.drop(columns = ['Sales','Invoice ID'])
X

,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,1/5/2019,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
1,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,3/8/2019,10:29:00 AM,Cash,76.40,4.761905,3.8200,9.6
2,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,3/3/2019,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4
3,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,1/27/2019,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
4,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,2/8/2019,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Giza,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,1/29/2019,1:46:00 PM,Ewallet,40.35,4.761905,2.0175,6.2
996,Cairo,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,3/2/2019,5:16:00 PM,Ewallet,973.80,4.761905,48.6900,4.4
997,Alex,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,2/9/2019,1:22:00 PM,Cash,31.84,4.761905,1.5920,7.7
998,Alex,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,2/22/2019,3:33:00 PM,Cash,65.82,4.761905,3.2910,4.1
999,Alex,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,2/18/2019,1:28:00 PM,Cash,618.38,4.761905,30.9190,6.6

#2. Feature Engineering

In [ ]:
# Convert data/time into useful features
df['Date'] = pd.to_datetime(df['Date'])
df["DayOfWeek"] = df["Date"].dt.dayofweek
df["Month"] = df["Date"].dt.month

df["Time"] = pd.to_datetime(df["Time"], format="%I:%M:%S %p")
df["Hour"] = df["Time"].dt.hour

In [ ]:
# Update features
X = df.drop(columns=["Sales", "Invoice ID", "Date", "Time"])

In [ ]:
X.info()
X.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Branch                   1000 non-null   object
 1   City                     1000 non-null   object
 2   Customer type            1000 non-null   object
 3   Gender                   1000 non-null   object
 4   Product line             1000 non-null   object
 5   Unit price               1000 non-null   float64
 6   Quantity                 1000 non-null   int64
 7   Tax 5%                   1000 non-null   float64
 8   Payment                  1000 non-null   object
 9   cogs                     1000 non-null   float64
 10  gross margin percentage  1000 non-null   float64
 11  gross income             1000 non-null   float64
 12  Rating                   1000 non-null   float64
 13  DayOfWeek                1000 non-null   int32
 14  Month                    1000 non-null   int32
 15  Hour                     1000 non-null   int32
dtypes: float64(6), int32(3), int64(1), object(6)
memory usage: 113.4+ KB

,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Payment,cogs,gross margin percentage,gross income,Rating,DayOfWeek,Month,Hour
0,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,Ewallet,522.83,4.761905,26.1415,9.1,5,1,13
1,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,Cash,76.40,4.761905,3.8200,9.6,4,3,10
2,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,Credit card,324.31,4.761905,16.2155,7.4,6,3,13
3,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,Ewallet,465.76,4.761905,23.2880,8.4,6,1,20
4,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,Ewallet,604.17,4.761905,30.2085,5.3,4,2,10

#3. Preprocessing

In [ ]:
# Separate Categorical and Numerical Features
categorical_Features = X.select_dtypes(include=['object']).columns
numerical_Features = X.select_dtypes(include=['int','float']).columns

In [ ]:
print(categorical_Features)
print(numerical_Features)

Index(['Branch', 'City', 'Customer type', 'Gender', 'Product line', 'Payment'], dtype='object')

In [ ]:
# Preprocessing Pipeline
categorical_transformer = OneHotEncoder(handle_unknown='ignore')
numerical_transformer = StandardScaler()
print(categorical_transformer)
print(numerical_transformer)

OneHotEncoder(handle_unknown='ignore')
StandardScaler()

In [ ]:
preprocessor = ColumnTransformer(
    transformers = [
        ('cat',categorical_transformer,categorical_Features),
        ('num',numerical_transformer,numerical_Features)
    ]
)

#4. Train/Test Split

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X, y, test_size=0.2, random_state=42)

#5. Model

In [ ]:
models = {
    'Linear Regression':LinearRegression(),
    'Random Forest':RandomForestRegressor(n_estimators=200, random_state=42),
    'Gradient Boosting':GradientBoostingRegressor(n_estimators=200, random_state=42)
}

#6. Training and Evaluation

In [ ]:
results = {}

for name, model in models.items():
  pipeline = Pipeline(steps=[('preprocessor',preprocessor),
                             ('model',model)])
  pipeline.fit(X_train,y_train)
  y_pred=pipeline.predict(X_test)

  results[name]={
      'RMSE': np.sqrt(mean_squared_error(y_test, y_pred)),
      'MAE': mean_absolute_error(y_test, y_pred),
      'R2': r2_score(y_test, y_pred)
  }

#7. Compare Result

In [ ]:
result_df = pd.DataFrame(results).T
result_df

                           RMSE           MAE        R2
Linear Regression  3.576617e-13  2.976641e-13  1.000000
Random Forest      1.350436e+00  7.777192e-01  0.999972
Gradient Boosting  2.185349e+00  1.630314e+00  0.999927